# Generated by Django 4.1.2 on 2022-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0005_alter_discipline_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
