# Generated by Django 4.1.2 on 2022-10-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0008_curator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
