# Generated by Django 4.1.1 on 2022-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrption',
            field=models.TextField(null=True),
        ),
    ]
