# Generated by Django 4.1.2 on 2022-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
